AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an S3 bucket
Parameters:
  AppENV:
    Type: String
    Default: DEV
  BucketName:
    Type: String
    Description: The bucket name
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'BucketName'
